package mail_registration

import "fmt"

const (
	LocaleEN = iota
	LocaleRS = iota
)

// It just works :D
// Look, ma, amma HTML programmer
//
// Yeah, I will refactor it using true html templates latter.
// TODO
func NewVerificationEmailBody(locale int, logo_path string) string {
	const head = `<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@500&display=swap" rel="stylesheet"> 
</head>\n`
	const styles = `<style>
body { display: flex; justify-content: center; align-items: center; background-color: #0C0E0F; padding: 0; margin: 0; color: #B4C1D4; font-family: 'Source Code Pro', monospace;}
.container { max-width: 600px; }
header { display: flex; justify-content: center; align-items: center; margin: 30px; }
.logo { height: 100%; max-width: 100% !important; margin-top: 5px; color: #E8646A; font-size: 3.6rem; }
.content { margin: 30px; margin-top: 0; border: 2px solid #232526; background-color: #0D0F12; border-radius: 10px; padding: 20px; font-size: 1.2rem;}
.button-container { display: flex; justify-content: center; align-items: center; margin: 30px;}
.button { padding: 20px; align-items: center; border-radius: 8px; border: 2px solid #749CBD; color: #749CBD; background-color: #5689A9; color: #0D0F12; text-decoration: none; font-weight: 800;}
footer { width: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; }
.heading { font-weight: 800; }
.social-networks { display: flex; flex-wrap: wrap; }
.social-network-icon { margin: 10px; color: #81C19B; text-decoration: none; }
</style>\n`

	var lang string
	var autoGeneratedEmail string
	var followMe string
	var registrationBtn string

	switch locale {
	case LocaleRS:
		lang = "rs"
		autoGeneratedEmail = "Zdravo,<br/><br/>Ovo je automatski generisana e-pošta za verifikaciju. Kliknite na dugme ispod da biste završili registraciju."
		registrationBtn = "Registracija"
		followMe = "Pratite me na društvenim mrežama:"
	default:
		lang = "en"
		autoGeneratedEmail = "Hi,<br/><br/>This is an automatically generated verification E-mail. Click on the button bellow to complite registration."
		registrationBtn = "Register"
		followMe = "Follow me on social networks:"
	}

	body := fmt.Sprintf(`<body>
	<div id="root">
		<header>
			<img src="%s" alt="CTF-1" class="logo">
		</header>
		
		<div class="content">
		%s

		<div class="button-container">
			<a href="https://" class="button">%s</a>
		</div>

		<footer>
			<div class="heading">%s</div>
			<div class="social-networks">
				<a href="https://gitlab.com/4nd3rs0n" class="social-network-icon">
					<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" viewBox="0 0 40 40">
  					<path d="M15.698 7.287 8.712.302a1.03 1.03 0 0 0-1.457 0l-1.45 1.45 1.84 1.84a1.223 1.223 0 0 1 1.55 1.56l1.773 1.774a1.224 1.224 0 0 1 1.267 2.025 1.226 1.226 0 0 1-2.002-1.334L8.58 5.963v4.353a1.226 1.226 0 1 1-1.008-.036V5.887a1.226 1.226 0 0 1-.666-1.608L5.093 2.465l-4.79 4.79a1.03 1.03 0 0 0 0 1.457l6.986 6.986a1.03 1.03 0 0 0 1.457 0l6.953-6.953a1.031 1.031 0 0 0 0-1.457"/>
					</svg>
				</a>
				<a href="https://github.com/4nd3r5on" class="social-network-icon">
					<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" viewBox="0 0 40 40">
  					<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
					</svg>
				</a>
				<a href="https://linkedin.com/in/4nd3rs0n" class="social-network-icon">
					<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" viewBox="0 0 40 40">
					  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
					</svg>
				</a>
				<a href="https://medium.com/@4nd3rs0n" class="social-network-icon">
					<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" viewBox="0 0 40 40">
  					<path d="M9.025 8c0 2.485-2.02 4.5-4.513 4.5A4.506 4.506 0 0 1 0 8c0-2.486 2.02-4.5 4.512-4.5A4.506 4.506 0 0 1 9.025 8zm4.95 0c0 2.34-1.01 4.236-2.256 4.236-1.246 0-2.256-1.897-2.256-4.236 0-2.34 1.01-4.236 2.256-4.236 1.246 0 2.256 1.897 2.256 4.236zM16 8c0 2.096-.355 3.795-.794 3.795-.438 0-.793-1.7-.793-3.795 0-2.096.355-3.795.794-3.795.438 0 .793 1.699.793 3.795z"/>
					</svg>
				</a>
			</div>
		</footer>
	</div>
	
	</div>
</body>`, logo_path, autoGeneratedEmail, registrationBtn, followMe)

	return fmt.Sprintf(`<html lang="%s">
	%s/n%s/n%s/n<html>`, lang, head, styles, body)
}
